baseURL = "https://www.hollielambert.com"
languageCode = "en-us"
title = "Hollie Lambert"
theme="archie"
copyright = "© Hollie Lambert"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate = 3 # articles per page

[params]
	mode = "toggle" # color-mode → light, dark, toggle or auto
	useCDN = false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "I like to build things. Mostly on the internet."
	favicon = "favicon.ico"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/hollielu"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/hollielulambert"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4